version: "3.9"

services:
  bean_db_test:
    image: postgres:16.6
    container_name: bean_postgres
    ports:
      - "5555:5432"
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - bean_postgres_data:/var/lib/postgresql/data
    networks:
      - bean-network

  bean_bot_test:
    image: na3810/bot_bean_ai:test
    container_name: bean_app
    restart: always
    env_file:
      - ./.env
    depends_on:
      - bean_db_test
    volumes:
      - bean_bot_downloads:/app/downloads
      - bean_bot_logs:/app/logs
      - /home/BeanAI_assistant_bot/test/fasolka.json:/app/db/fasolka.json
      - /home/BeanAI_assistant_bot/test/faiss_index_RU:/app/faiss_index_RU
    networks:
      - bean-network

networks:
  bean-network:

volumes:
  bean_postgres_data:
  bean_bot_downloads:
  bean_bot_logs:

