version: "3.9"

services:
  db:
    image: postgres:16.6
    container_name: bean_postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - bean_postgres_data:/var/lib/postgresql/data
    networks:
      - bean-network

  bot:
    build: .
    container_name: bean_app
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - bean_bot_downloads:/app/downloads
      - bean_bot_logs:/app/logs
    networks:
      - bean-network

networks:
  bean-network:

volumes:
  bean_postgres_data:
  bean_bot_downloads:
  bean_bot_logs:

